## name :crimson-gold
foreground              #bebebe
background              #121212

selection_foreground    #bebebe
selection_background    #333333

cursor                  #eaeaea
cursor_text_color       #121212

active_tab_foreground   #bebebe
active_tab_background   #121212

inactive_tab_foreground #8a8a8d
inactive_tab_background #333333

# black
color0  #333333
color8  #8a8a8d

# red
color1  #EE3333
color9  #FF3333

# green
color2  #FFC107
color10 #FFC107

# yellow
color3  #b91c1c
color11 #b90a0a

# blue
color4  #e68e0d
color12 #f59e0b

# magenta
color5  #D35F5F
color13 #B91C1C

# cyan
color6  #EE0000
color14 #FF4444

# white
color7  #bebebe
color15 #ffffff