; note: most of the accent colors are set to the green of that color scheme, feel free to change it to your preferred color

[Crimson Gold]
accent             = f8c22D
accent-active      = D8B22D
accent-inactive    = 311111
banner             = ffdd55
border-active      = ffdd55
border-inactive    = 807000
header             = D8B22D
highlight          = 550000
main               = 300808
notification       = 4687d6
notification-error = e22134
subtext            = f00000
text               = ffdd55

